spring.application.name=progress-service
server.port=8084

spring.datasource.url=jdbc:mysql://localhost:3306/progress_db
spring.datasource.password=password
spring.datasource.username=root

spring.security.user.name=user
spring.security.user.password=000
