spring:
  application:
    name: progress-service
  datasource:
    password: password
    url: jdbc:mysql://${eureka.instance.hostname}:3306/progress_db
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  security:
    user:
      name: user
      password: 000
  config:
    import: optional:configserver:http://localhost:8092
server:
  port: 8084

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8091/eureka


# discovery-service 8761
